version: '3.3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"

  mariadb:
    build:
      context: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    

volumes:
  mariadb:
